# версия синтаксиса
version: '3'

# в этом блоке мы описываем контейнеры, которые будут запускаться
services:
  #контейнер с Nginx
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: myapp/nginx
    container_name: topvisor_webserver
    # проброс портов
    ports:
      - "80:80"
    volumes:
       - .:/data/mysite.local
    networks:
      - app-network

  #Контейнер с PHP-FPM, назовём его app
  php-fpm:
    # Если нет секции build, то система будет искать образ в репозиториях
    build:
      context: ./fpm
      dockerfile: Dockerfile
    image: myapp/php # имя будущего образа
    container_name: topvisor_php-fpm # имя контейнера после запуска
    volumes:
       - .:/data/mysite.local
    # мы можем создать для контейнеров внутреннюю сеть
    networks:
      - app-network


#Docker Networks
networks:
  app-network:
    driver: bridge